### ISSUE TITLE
Asset re-importing does not work

### ISSUE THREAD

**Issue by 123099** [DavidColson/UnrealInk#2]
When dragging an ink file to the editor for the very first time, everything works great - a UStoryAsset file is created properly.
When modifiying the source ink file afterwards, Unreal does show a notification that is is processing resources, but the asset factory create file method is not called, and the UStoryAsset is not updated.

**Comment by DavidColson** [comment]
This is now resolved. It'll auto reimport when scanning the content folder, or you can right click on the asset and click re-import
